index:
  path: /
  controller: App\Controller\IndexController::index


session_user:
  path: /session/{id}
  controller: App\Controller\SessionController::user
  methods: GET

session_user_create:
  path: /session/users
  controller: App\Controller\SessionController::create
  methods: POST

session_user_delete:
  path: /session
  controller: App\Controller\SessionController::delete
  methods: DELETE

user_create:
  path: /user
  controller: App\Controller\UserController::create
  methods: POST

users_read:
  path: /users
  controller: App\Controller\UserController::readAll
  methods: GET

users_birthdays:
  path: /users/birthday
  controller: App\Controller\UserController::readBirthdays
  methods: GET

user_read:
  path: /users/{id}
  controller: App\Controller\UserController::read
  methods: GET

user_update:
  path: /users/{id}
  controller: App\Controller\UserController::update
  methods: PATCH

request_create:
  path: /request
  controller: App\Controller\RequestController::create
  methods: POST

requests_read:
  path: /requests
  controller: App\Controller\RequestController::readAll
  methods: GET

requests_read_month:
  path: /{year}/{month}/{department}/requests/users/{id}
  controller: App\Controller\RequestController::readMonth
  methods: GET

requests_read_employee:
  path: /requests/users/{id}
  controller: App\Controller\RequestController::readEmployee
  methods: GET

requests_read_unapproved:
  path: /requests/unapproved
  controller: App\Controller\RequestController::readUnapproved
  methods: GET

request_read:
  path: /requests/{id}
  controller: App\Controller\RequestController::read
  methods: GET

request_update:
  path: /requests/{id}
  controller: App\Controller\RequestController::update
  methods: PATCH

request_update_approve:
  path: /requests/{id}/approve
  controller: App\Controller\RequestController::approve
  methods: PATCH

request_delete:
  path: /requests/{id}
  controller: App\Controller\RequestController::delete
  methods: DELETE

notice_create:
  path: /notice
  controller: App\Controller\NoticeController::create
  methods: POST

notices_read:
  path: /notices
  controller: App\Controller\NoticeController::readAll
  methods: GET

notice_read:
  path: /notices/{id}
  controller: App\Controller\NoticeController::read
  methods: GET

notice_delete:
  path: notices/{id}
  controller: App\Controller\NoticeController::delete
  methods: DELETE
