index:
  path: /
  controller: App\Controller\IndexController::index

login:
  path: /login
  controller: App\Controller\POSTS::login

user:
  path: /user
  controller: App\Controller\GETS::user

userbyemail:
  path: /email
  controller: App\Controller\GETS::userByEmail

users:
  path: /users
  controller: App\Controller\GETS::users

logout:
  path: /logout
  controller: App\Controller\GETS::logout

register:
  path: /register
  controller: App\Controller\POSTS::register

update:
  path: /update
  controller: App\Controller\POSTS::update

request:
  path: /request
  controller: App\Controller\POSTS::request

hours:
  path: /hours
  controller: App\Controller\POSTS::hours

monthrequests:
  path: /monthrequests
  controller: App\Controller\POSTS::requestsByMonth

requests:
  path: /requests
  controller: App\Controller\GETS::requests

employeerequests:
  path: /employeerequests
  controller: App\Controller\POSTS::requestsByEmployee

birthdays:
  path: /birthdays
  controller: App\Controller\GETS::birthdaysByMonth

unapproved:
  path: /unapproved
  controller: App\Controller\GETS::unapproved

approve:
  path: /approve
  controller: App\Controller\POSTS::approve

deny:
  path: /deny
  controller: App\Controller\POSTS::deny
